# -*- coding: utf-8 -*-
"""H2O AutoML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TwCtM6swaDjhg6LfHSp0ihL5XcmpGqvf
"""

#============================
# Step 1: Install packages
#============================

pip install h2o

pip install h2o auto-sklearn tpot mljar-supervised

pip install pandas numpy scikit-learn matplotlib

#=================================
# Step 2: Import libraries
#=================================

import h2o
from h2o.automl import H2OAutoML
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

print("=== AutoML Demo with H2O ===")

#=================================
# Step 3: Load YOUR dataset
#=================================

print("1. Loading real dataset...")
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("homework.csv")
df = df.drop(columns=["rownames"])
df = df.replace({"yes": 1, "no": 0})

X = df.drop(columns=["price"])
y = "price"

print(f"Dataset shape: {df.shape}")
print("First 5 rows:")
print(df.head())

#=================================
# Step 4: Initialize H2O
#=================================

print("\n2. Initializing H2O...")
h2o.init()

# Convert pandas DataFrame to H2O Frame
h2o_df = h2o.H2OFrame(df)

# Features for AutoML
x = h2o_df.columns
x.remove(y)

print(f"Features: {len(x)}")
print(f"Target: {y}")

#=================================
# Step 5: Split the data
#=================================

train, test = h2o_df.split_frame(ratios=[0.8], seed=42)
print(f"Training set: {train.shape[0]} rows")
print(f"Test set: {test.shape[0]} rows")

#=================================
# Step 6: Run AutoML (Regression)
#=================================

print("\n3. Running AutoML ...")

aml = H2OAutoML(
    max_models=10,          # Maximum number of models
    seed=42,                # Reproducibility
    max_runtime_secs=300,   # 5 minutes max runtime
    exclude_algos=["GLM"],  # Optional, to speed up
    verbosity="info"
)

aml.train(x=x, y=y, training_frame=train)

#=================================
# Step 7: Display results
#=================================

print("\nLeaderboard (Top Models):")
lb = aml.leaderboard
print(lb.head())

# Best model
best_model = aml.leader
print(f"\nBest Model: {best_model.model_id}")

#=================================
# Step 8: Make predictions
#=================================

predictions = best_model.predict(test)
print("\nPredictions sample:")
print(predictions.head())

#=================================
# Step 9: Model performance
#=================================

performance = best_model.model_performance(test)
print("\nModel Performance:")
print(performance)

#=================================
# Step 10: Shutdown H2O
#=================================

print("\nShutting down H2O...")
h2o.cluster().shutdown()

print("\n=== AutoML Complete ===")